CONNECT_TO_DRONE = True
WIFI_SSID = "TELLO-61EE08"
BATTERY_FAILSAFE_PERCENTAGE = 15 
EMERGENCY_LAND_BATTERY = 5 
FORWARD_VELOCITY = 25  # cm/s (drone forward speed)
YAW_VELOCITY = 40      # deg/s (drone yaw)
PID_GAINS = {
    "P": 0.25,
    "I": 0.0,
    "D": 0.1
}
FACE_TARGET_AREA = 62000
GRID_CELL_SIZE_CM = 50   
SEARCH_PATTERN_RADIUS_M = 10
FRAME_WIDTH = 960
FRAME_HEIGHT = 720
CONFIDENCE_THRESHOLD = 0.6  
THUMB_TUCK_PROXIMITY_THRESHOLD = 0.08
FACE_CASCADE_PATH = "models/haarcascade_frontalface_default.xml" 
MAP_SIZE_METERS = 10 